# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160108_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(related_name='_category_parent_+', to='shop.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shop.Category'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
